name: xlsx-import

on: [push, pull_request]

defaults:
  run:
    working-directory: ./packages/xlsx-import

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        node-version: [8.x, 9.x, 10.x, 11.x, 12.x, 13.x, 14.x] # version 8 and 9 isn't supported in ExcelJS as default - may I resolve it further (or ignore)
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: Check lint
      run: npm run lint
    - name: Check build
      run: npm run build
    - name: Check unit & integration tests with coverage
      run: npm run coverageReport
    - name: Publish coverage report
      continue-on-error: true
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CI: true
